# Generated by Django 4.2.3 on 2023-07-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0004_remove_category_item_item_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.AddField(
            model_name='item',
            name='categories',
            field=models.ManyToManyField(related_name='categories', to='shopping_app.category'),
        ),
    ]
