# Generated by Django 4.2.3 on 2023-07-24 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0005_remove_item_category_item_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelForPivot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping_app.category')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping_app.item')),
            ],
        ),
    ]
