# Generated by Django 4.2.3 on 2023-07-24 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0006_modelforpivot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='categories',
            field=models.ManyToManyField(to='shopping_app.category'),
        ),
    ]
